#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
#
# NOTE: gradle/wrapper/gradle-wrapper.jar is a binary produced by Gradle and is
# not committed here. Regenerate the wrapper once with an installed Gradle:
#     gradle wrapper --gradle-version 8.9
# or simply open the project in Android Studio, which regenerates it on sync.
#
set -e

APP_HOME=$(cd "$(dirname "$0")" >/dev/null && pwd)
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$CLASSPATH" ]; then
  echo "gradle-wrapper.jar is missing." >&2
  echo "Run 'gradle wrapper --gradle-version 8.9' or open the project in Android Studio." >&2
  exit 1
fi

if [ -n "$JAVA_HOME" ]; then
  JAVACMD="$JAVA_HOME/bin/java"
else
  JAVACMD="java"
fi

exec "$JAVACMD" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
