@rem Gradle startup script for Windows generated by Gradle.
@rem gradle-wrapper.jar is not committed. Regenerate once with:
@rem   gradle wrapper --gradle-version 8.9
@rem or open the project in Android Studio.
@if "%DEBUG%"=="" @echo off
@setlocal
set DIRNAME=%~dp0
set APP_HOME=%DIRNAME%
set CLASSPATH=%APP_HOME%gradle\wrapper\gradle-wrapper.jar
if not exist "%CLASSPATH%" (
  echo gradle-wrapper.jar is missing. Run "gradle wrapper --gradle-version 8.9" or open in Android Studio.
  exit /b 1
)
if defined JAVA_HOME (set JAVACMD=%JAVA_HOME%\bin\java.exe) else (set JAVACMD=java.exe)
"%JAVACMD%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*
@endlocal
